travis:
  secure:
    BINSTAR_TOKEN: Lx8Ywi+xlFFYXsOqHGG5PlaYWyliW1jt2IyGJoGxT06V4tyxzKMWDDuPv40vJdABihUM0MywaATIf5ZZ5kIxEzLImgVVUfC5bBYKl753gGH8N97DlvM4KKCyWG01Gvp9lBXcAirem8ALp0spobcMOtLCD+BOsWOWrcVczLKwUdxoGLT9M4U+/08m5tpRXTIbRYll7jW7nwCQ5fXLjvk8TqZBHKkAubE3eLvw5fSzFNGTq1ws961OSl0X23wa34eGVOSUM+PzBzan7eXJvtOAnxv03g5aIUbZav5PQa3MSPhwwE20plbcZpmDnWyOHLV1HPExPkKDFCVTCxBxrS9I8uspOGfMPY93o2yZBvi6Dmhx4JMb2ejXyNiu7FvBWKcZdYau9OrNd9JWybE4T30Xf3hzgYo4XrbZ2xE4Y655wDedg0x6Q5fcARWT3lmuHtn+8DrnXYUgAfE0qL2ljL0HZanKx/BZjtdiKJn6QG6a4rvWy8SxOUa474pNdDgt+w/itp6R4nuPsQcNE/TdwFCv4NYv/c2sRG5lF0IAvOozjC0CO9T1e3aLfjrMjy0RACRk0ICx39N81v9PtjDdBy9H21cN8eK2iRF9zmswf4XuYrHTSmQLU44//42BfYm5wVdkwFlBkkIm8C3X4FahXrxOHnDEDrrmnRyOMgD3M+X49H0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
