travis:
  secure:
    BINSTAR_TOKEN: xpwUNT0Wy/AH7t4RX+lgJ0oaaxzMW06ArF30/GceYb5ou45dVPFOATD2+DejWo7XGCjv/kYUMUffZjGCANTCD3iXpli5B+b/7LzmlJ5cZIaLJ1XTuHWivXxuOY2LFoMplKEuOa8fs2W1gw9GnHoHtxb+jj8AsiivnbESLcuO9U5qfzGv3vUjYupkFcFvVjpSHRCH1RSrOnClRE017xI0gVbkpUrKcasxe/lTC9ZjPhWn37a/g1TXW8e1qVIjuD2OAft2KKf+4OrFIbf0gWUpXJNPVj80rvYgnvTJHNk8EAFWyHg8GxKsHGDnUCfQ3eWUkp6oz+g2yUz1Nyw7MtvZVHKStZEc3OYE2twH+Xtbog/mkZrc281kR+Hly56vFwx83XbI355RswHPZzr/HL+HlCL9c48qkAabk/0wNiZtPiQUnebMScAOm4uMPRNTEIRPPRx0/XULZbgQAN/4V7OnYT60cxLjXeGkKesqyTlRys8KS7poZ0Q4dXba02DkcPz+jXmiAIZ3huTyk1rv0Fx3c0CwWWXWJpK6dKXHuNr75lnfBbjihcBZabI2dohQLTSNXlBTJVUrhts9gD9RJH9a1T/k9Odad+/TClsMAuS6Yt+0yR48Au5jYw7iuIUPn/RrvSkIe3TxlJSiM2srYBYRQ6GB8IbFZ3UpZkMFcngxA9s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
