travis:
  secure:
    BINSTAR_TOKEN: SMi6XD07eo5bx4CbqINC8ojw5hn0CUR9kv1NjxhHqjG+rR6/t7c93iXuxLwVyHBmjR6J3PIqOgvrw7afDdRc/WqWhqXDcJHSI5OyyMcLnHl9Eaas9T+REb8Q2t8g94Jir5f7NFDItCzWKjenMSA2IKfXJCcMNKnaSoshuh/c9CYJIDTQHs5QddOZ25SAUMQP80vo3fwtC49lXCqHsv5VlUJ4YzcTOKIYndG/wHm0z1Gcr0j4EOFJ29b+GJcKI6A5jC4YSx2XWmkvHWHdLEyp8F+rxnu6aMeCykelhaKGRv/ndMdawU8EJFDKSH71BX2nVlSEbbNmUHd/K7477D4PH5K561AeATEFY5PTpFMFVw/T7l5BKglghnP2nDSv4rJ8XYgI6JcsSd+eNiGLO370Wy5uFFUXF94C9tsfdG/18CrWAZq9jt3PzoB0T5XzFUbwN77Fr0F63QtocXmonL4XmXosVaFGc0pLVRCB0jVyaLuZo2kQQQGZThv2HXFOALf8v6h7VJfUp+2KVGFjhkjufmUG7O2O1qZZO05vhPBmEa+uk9GxNkn0Itbnw3wJ9H5FeyYExLT9fgA0FoIuueBqVuYq91xR3a97utTj3jEVXc4yuvR+LqCQSeAt6cEQWwOGxs10WTqem2Sxm3XxPZEDzaRAoDKZsjcvT7ydOKJiRpY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
